# -*- coding: utf-8 -*-
"""anomaly_detection.ipynb

Automatically generated by Colab.


"""

# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data_path = '/content/FinancialMarketData.csv'  # Adjust path if necessary
data = pd.read_csv(data_path)

# Explore the dataset
print("Dataset Head:")
print(data.head())
print("\nDataset Info:")
data.info()

# Check for missing values
print("\nMissing Values:")
print(data.isnull().sum())

# Clean and preprocess the dataset
# Drop irrelevant or unnamed columns
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]

print("\nCleaned Dataset Columns:")
print(data.columns)

# Ensure the target column exists
# Modify the target column name as per your dataset
target_column = 'Crash'  # Change this to match your dataset
if target_column not in data.columns:
    raise KeyError(f"Target column '{target_column}' not found in dataset. Available columns: {data.columns}")

# Data preprocessing
X = data.drop(columns=[target_column])  # Features
y = data[target_column]  # Target

# Handle any non-numeric data
X = pd.get_dummies(X, drop_first=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model selection and training
# Using Random Forest as an example
model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

# Model evaluation
y_pred = model.predict(X_test_scaled)

print("\nConfusion Matrix:")
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

# Feature importance visualization
feature_importances = model.feature_importances_
features = X.columns

plt.figure(figsize=(10, 6))
plt.barh(features, feature_importances, color='skyblue')
plt.title('Feature Importances')
plt.xlabel('Importance')
plt.ylabel('Features')
plt.show()

# Save the model
import joblib
model_filename = 'anomaly_detection_model.pkl'
joblib.dump(model, model_filename)
print(f"Model saved as {model_filename}")
